### PR TITLE
[NWS-1224][NWS-1543] The attachments code must to be equal to expense code on onedrive

### PR DESCRIPTION
**Pull request by WilamisAviz15**

### CODE REVIEW

**Comment by WilamisAviz15** [comment]
Added att to existing expense 
image

**Comment by WilamisAviz15** [comment]
Ao apagar a despesa:
image

**Comment by WilamisAviz15** [comment]
Ao criar uma nova despesa com anexos:
image

**Comment by WilamisAviz15** [comment]
image

**Review by EduhFarias — APPROVED** [review]

**Review by augustoicaro — APPROVED** [review]

**Pull request merged**
